function resultado(){
    let c=0;
     if(document.getElementById('r1').checked){
         c++;
     }
     if(document.getElementById('r4').checked){
         c++;
     }
     if(document.getElementById('r6').checked){
         c++;
     }
     if(document.getElementById('r8').checked){
         c++;
     }
     if(document.getElementById('r10').checked){
         c++;
     }
     if(document.getElementById('r11').checked){
         c++;
     }
     if(document.getElementById('r13').checked){
         c++;
     }
     if(document.getElementById('r16').checked){
         c++;
     }
     if(document.getElementById('r18').checked){
         c++;
     }
     if(document.getElementById('r19').checked){
         c++;
     }
     if(document.getElementById('r22').checked){
         c++;
     }
     if(document.getElementById('r23').checked){
         c++;
     }
     if(document.getElementById('r26').checked){
         c++;
     }
     if(document.getElementById('r27').checked){
         c++;
     }
     if(document.getElementById('r30').checked){
         c++;
     }
     if(document.getElementById('r34').checked){
         c++;
     }
     if(document.getElementById('r36').checked){
         c++;
     }
     if(document.getElementById('r37').checked){
         c++;
     }
     if(document.getElementById('r40').checked){
         c++;
     }
     if(document.getElementById('r41').checked){
         c++;
     }
     if(document.getElementById('r43').checked){
         c++;
     }
     if(document.getElementById('r45').checked){
         c++;
     }
     if(document.getElementById('r47').checked){
         c++;
     }
     if(document.getElementById('r49').checked){
         c++;
     }
     if(document.getElementById('r51').checked){
         c++;
     }
     if(document.getElementById('r53').checked){
         c++;
     }
     if(document.getElementById('r56').checked){
         c++;
     }
     if(document.getElementById('r57').checked){
         c++;
     }
     if(document.getElementById('r60').checked){
         c++;
     }
     if(document.getElementById('r61').checked){
         c++;
     }
     if(document.getElementById('r64').checked){
         c++;
     }
     if(document.getElementById('r65').checked){
         c++;
     }
     if(document.getElementById('r68').checked){
         c++;
     }
     if(document.getElementById('r69').checked){
         c++;
     }
     if(document.getElementById('r72').checked){
         c++;
     }
     if(document.getElementById('r74').checked){
         c++;
     }
     if(document.getElementById('r77').checked){
         c++;
     }
     if(document.getElementById('r78').checked){
         c++;
     }
     if(document.getElementById('r81').checked){
         c++;
     }
     if(c<19){
		swal("Ups.. Segui intentando","Tenes "+c+" de 39 puntos","error");
	}
	else{
swal("Felicidades!! Pasaste", "Tenes "+c+" de 39 puntos","success",
        {closeOnClickOutside: false}).then((value)=>{
            window. location = "https://overtime21.000webhostapp.com/pagina4.html";
        });	}
 }